t = input('Digite algo: ')
print('É um número? ', t.isnumeric())
print('Está maiúsculo? ', t.isupper())
print('É alfabético? ', t.isalpha())
print('É alfanumérico? ', t.isalnum())
print('Só tem espaços? ', t.isspace())
print('Está em minúsculas? ', t.islower())
print('Está capitalizada? ', t.istitle())
